openapi: 3.0.3

info:
  title: User OTP Generation API
  version: 1.0.0

servers:
  - url: 'http//localhost:{port}'
    variables:
      port:
        default: '8080'
    description: Dev with data on localhost
  - url: '{protocol}//{host}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      host:
        default: "microservices.deepdrimz.com"
      port:
        default: '8080'
    description: Dev with data on remote staging

tags:
  - name: Generate OTP
    description: Endpoint feature to genrate and send OTP.

paths:
  /iam/authentications/otp/{recipient}:
    post:
      summary: Generate and Send OTP
      description: Allows a user to request an OTP for various actions requiring verification.
      parameters:
        - name: recipient
          in: path
          required: true # Set to true if it's a mandatory parameter
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateOtpRequestDTO'
              
      responses:
        '201':
          description: OTP generation successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Informational message confirming OTP generation.
                  otp:  # Replaced with OTP object
                    type: object
                    $ref: '#/components/schemas/GenerateOtpResponseDTO'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message describing the issue (e.g., missing field, invalid format).
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: User not found or action identifier not recognized.
        '429':
          description: Too Many Requests.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: User exceeded allowed OTP requests within the timeframe.
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Generic error message indicating server-side issue.

components:
  schemas:
    GenerateOtpRequestDTO:
      type: object
      $ref: './schemas.yaml#/components/schemas/GenerateOtpRequestDTO'
    GenerateOtpResponseDTO:
      type: object
      allOf:
        - $ref: "../schemas.yaml#/components/schemas/ResponseSuccessDTO"
      properties:
        data:
          allOf:
            - $ref: './schemas.yaml#/components/schemas/OtpIdDTO'
            - $ref: './schemas.yaml#/components/schemas/OtpDTO'
